---
  - name: Change mongoDB config file
    vars:
      mongo_bind_ip: 0.0.0.0
      mongo_port: 27017
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify: restart mongod

  - name: Enable mongod Service
    systemd: name=mongod enabled=yes
