---
dependency:
    name: galaxy
driver:
    name: gce
    credentials_file: gce_credentials.json
    image_family: ubuntu
    machine_type: g1-small
    project_id: infra-207721

lint:
    name: yamllint
platforms:
    - name: instance
provisioner:
    name: ansible
    lint:
        name: ansible-lint
scenario:
    name: default
verifier:
    name: testinfra
    lint:
        name: flake8
