---
- name: Converge
  hosts: all
  become: true
  vars:
      mongo_bind_ip: 0.0.0.0
  pre_tasks:
      - name: install python if necessary
        raw: which python || (apt-get update && apt-get install -y python-minimal)
  roles:
    - role: db
